### Site Settings ###
title               : Jessy Le Du-Carrée
description         : >-
                      Scientist turned Data Professional — passionate about uncovering insights through data.
baseurl             : ""                                # Empty because you're hosting at jessy-ledu.github.io
repository          : jessy-ledu/jessy-ledu.github.io   # Your GitHub Pages repo
remote_theme        : yousinix/portfolYOU
open_new_tab        : true                              # Set true to open external URLs in a new tab


### Plugins ###
plugins:
  - jemoji                                              # Enables GitHub-style emoji support


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from the navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md

### Author Info ###
author:
  name              : Jessy Le Du-Carrée
  image             : https://jessy-ledu.github.io/assets/image1_small.png
# behance           : your_username
# dribbble          : your_username
  email             : jessy.ledu@gmail.com
# facebook          : your_username
  github            : jessy-ledu
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : Jessy Ledu-Carrée
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title                                 # Blog posts permalink structure


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Comment system (optional) — leave blank or remove if unused


### Analytics ###
analytics:
  enabled: false                                        # Enable if you want Google Analytics
  google:
    tracking_id: your-google-tracking-id


### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: false                                        # Set to true if you'd like to enable donation support
  username: your_username
  color: "#007bff"
  message: "Thank you for visiting."                    # Message near the donation button
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true if using Disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
